table DIM_DATE
	lineageTag: a3b93883-c25c-426b-9325-208b94717809
	dataCategory: Time

	column DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0214109e-17a8-430e-8792-bc435336ebb0
		summarizeBy: none
		sourceColumn: DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column DATE
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 90987295-c156-42e9-a5ca-17d36a3142cd
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YEAR
		dataType: int64
		lineageTag: 9d110763-5140-4441-83fa-fb8a0c5ee1d9
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUARTER
		dataType: int64
		lineageTag: 82f5ccc2-937a-4b65-b0a9-f8177fe29d4b
		summarizeBy: none
		sourceColumn: QUARTER

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MONTH
		dataType: int64
		lineageTag: e1b43a5d-6430-47f3-b6e7-92fe3e66fa73
		summarizeBy: none
		sourceColumn: MONTH

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YEAR_MONTH
		dataType: dateTime
		formatString: Long Date
		lineageTag: f937ba13-2130-4420-aaf6-fb8e52a4171d
		summarizeBy: none
		sourceColumn: YEAR_MONTH
		sortByColumn: YearMonthSort

		changedProperty = DataType

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_OF_YEAR
		dataType: int64
		lineageTag: df5cec15-28bb-4bd9-a063-f3d2b276f19e
		summarizeBy: none
		sourceColumn: WEEK_OF_YEAR

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DAY_NAME
		dataType: string
		lineageTag: 96fffc45-285d-4d3a-8572-f6b3779d2039
		summarizeBy: none
		sourceColumn: DAY_NAME

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column DAY_OF_WEEK
		dataType: int64
		lineageTag: e6221ea8-b2b2-4100-86db-64c07e4ee6c0
		summarizeBy: none
		sourceColumn: DAY_OF_WEEK

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearMonthSort = FORMAT([Date], "yyyyMM")
		dataType: int64
		formatString: 0
		lineageTag: 943861dd-6f1c-4de2-875f-65786f88cad1
		summarizeBy: sum

		changedProperty = SortByColumn

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE = m
		mode: import
		source =
				let
				    Source = fnLoadCsv("dim_date.csv"),
				    UpperHeaders = Table.TransformColumnNames(Source, Text.Upper),
				
				    #"Changed Type" = Table.TransformColumnTypes(
				        UpperHeaders,
				        {
				            {"DATE_KEY", Int64.Type},
				            {"DATE", type date},
				            {"YEAR", Int64.Type},
				            {"QUARTER", Int64.Type},
				            {"MONTH", Int64.Type},
				            {"YEAR_MONTH", type text},
				            {"WEEK_OF_YEAR", Int64.Type},
				            {"DAY_NAME", type text},
				            {"DAY_OF_WEEK", Int64.Type}
				        },
				        "en-US"
				    )
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

