table Scenario_FreightSurcharge
	lineageTag: e5f6a7b8-c9d0-1234-efab-234567890145

	measure 'Selected Freight Surcharge %' = SELECTEDVALUE ( Scenario_FreightSurcharge[Value], 0 )
		formatString: 0%
		displayFolder: L. Scenario Planning
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012367

	column Value
		formatString: 0%
		lineageTag: 8c2f7672-31f7-4e94-8c4f-4d6d62d6ffdd
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0,
				  "kind": 1
				}

	partition Scenario_FreightSurcharge = calculated
		mode: import
		source = GENERATESERIES ( 0, 0.50, 0.05 )

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation ParameterMetadata = {"version":3,"kind":"Numeric"}

